name: CI

on:
  push:
    branches-ignore:
      # Dependabot always opens a PR so no need to trigger this twice
      - 'dependabot/**'
  pull_request:

env:
  CI: true

jobs:
  pre_job:
    name: Check for unecessary runs
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v4.0.0
        with:
          cancel_others: 'true'
          concurrent_skipping: 'true'
          skip_after_successful_duplicate: 'true'
          paths_ignore: '["**/README.md"]'
          do_not_skip: '["pull_request"]'

  build-and-test:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 16.x]
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.2.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.2.0
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install --no-fund
      - run: npm test
      - name: Run tests for ESM
        run: npm run test:esm
        if: matrix.node-version != '10.x'

  eslint:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.2.0
      - name: Use Node.js 16
        uses: actions/setup-node@v3.2.0
        with:
          node-version: 16
      - run: npm install --no-audit --ignore-scripts --no-fund
      - run: npm run lint

  clang-format:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.2.0
      - name: Install clang-format
        run: sudo apt-get install clang-format
      - name: Check style
        run: clang-format --style=Google --Werror --dry-run src/zopflipng.cc
