name: CI

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

env:
  CI: true

permissions: {}

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.1.0
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install --no-fund
      - run: npm test
      - name: Run tests for ESM
        run: npm run test:esm

  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - name: Use Node.js 22
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 22
      - run: npm install --no-audit --ignore-scripts --no-fund
      - run: npm run lint

  clang-format:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - name: Install clang-format
        run: sudo apt-get install clang-format
      - name: Check style
        run: clang-format --style=Google --Werror --dry-run src/zopflipng.cc
