name: Publish a release

on:
  release:
    types: [published]

jobs:
  prebuild:
    name: Prebuild native module
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-13
          - windows-latest
        architecture:
          - x64
        # also get windows-x86:
        include:
          - os: windows-latest
            architecture: x86
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Use Node.js 22 - ${{ matrix.architecture }}
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 22
          architecture: ${{ matrix.architecture }}

      - name: Install dependencies
        run: npm install --ignore-scripts --no-fund

      - name: Prebuild
        run: npm run prebuild

      - name: Upload prebuilds
        uses: actions/upload-artifact@v3
        with:
          name: prebuild-${{ runner.os }}-${{ matrix.architecture }}
          path: prebuilds
          retention-days: 1

  prebuild_docker:
    name: Prebuild container modules
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - almalinux-devtoolset11
          - alpine
          - linux-arm64-lts
          - linux-armv7
    container:
      image: ghcr.io/prebuild/${{ matrix.image }}
      options: --user root
    steps:
      - name: Install git
        if: matrix.image == 'almalinux-devtoolset11'
        run: microdnf install -y git

      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Use Node.js 22
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install --ignore-scripts

      - name: Prebuild
        run: npm run prebuild

      - name: Upload prebuilds
        uses: actions/upload-artifact@v3
        with:
          name: prebuild-${{ matrix.image }}
          path: prebuilds
          retention-days: 1

  assemble:
    name: Assemble prebuilt binaries
    needs: [ prebuild, prebuild_docker ]
    runs-on: ubuntu-latest
    steps:
      - name: Download prebuilt binaries
        uses: actions/download-artifact@v3

      - name: Move binaries to one folder
        run: mkdir prebuilds && cp -rl ./prebuild-*/* ./prebuilds/

      - name: Upload prebuilds
        uses: actions/upload-artifact@v3
        with:
          name: prebuilds
          path: prebuilds

  publish:
    name: Publish
    needs: assemble
    environment: npm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Use Node.js 22
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 22

      - name: Download prebuilt binaries
        uses: actions/download-artifact@v3
        with:
          name: prebuilds
          path: prebuilds

      - name: Publish on npm
        uses: JS-DevTools/npm-publish@v1.4.3
        with:
          token: ${{ secrets.NPM_TOKEN }}
