name: Release, plase

on:
  push:
    branches:
      - main

jobs:
  release-please:
    name: Release, plase
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2.29.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: node-zopflipng
          bump-minor-pre-major: true
