name: Release, plase

on:
  push:
    branches:
      - main

jobs:
  release-please:
    name: Release, plase
    environment: GitHub
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v3.7
        with:
          token: ${{ secrets.GH_PERSONAL_TOKEN }}
          release-type: node
          package-name: node-zopflipng
          bump-minor-pre-major: true
